env: "local"

storage:
  postgres:
    host: localhost
    port: 5432
    username: postgres
    password: passwd
    database: gerc

http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s

retry:
  max_attempts: 5
  timeout: 5s
